import type { ReactNode } from 'react';
import Link from 'next/link';
import './globals.css';

export const metadata = {
  title: 'AI Services Marketplace',
  description:
    'Post AI service requests, get an instant AI brief, receive provider proposals, accept the best one.',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <header className="site-header">
          <Link href="/" className="brand">
            AI Services Marketplace
          </Link>
          <nav className="nav">
            <Link href="/customer">Customer</Link>
            <Link href="/provider">Provider</Link>
            <Link href="/admin">Admin</Link>
          </nav>
        </header>
        <main className="container">{children}</main>
        <footer className="site-footer">
          <span className="muted">Generated by the Software Factory · local SQLite profile</span>
        </footer>
      </body>
    </html>
  );
}
